//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daishi.PaySharp.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daishi.PaySharp.UnitTests.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKEN=EC%2d080143372V8487112&amp;BILLINGAGREEMENTACCEPTEDSTATUS=0&amp;CHECKOUTSTATUS=PaymentActionNotInitiated&amp;TIMESTAMP=2015%2d08%2d31T11%3a07%3a13Z&amp;CORRELATIONID=cdb26170126a4&amp;ACK=Success&amp;VERSION=93&amp;BUILD=000000&amp;EMAIL=daishi%2esystems%2dbuyer%40gmail%2ecom&amp;PAYERID=UPMHHXJ72R4EG&amp;PAYERSTATUS=verified&amp;FIRSTNAME=test&amp;LASTNAME=buyer&amp;COUNTRYCODE=US&amp;SHIPTONAME=test%20buyer&amp;SHIPTOSTREET=1%20Main%20St&amp;SHIPTOCITY=San%20Jose&amp;SHIPTOSTATE=CA&amp;SHIPTOZIP=95131&amp;SHIPTOCOUNTRYCODE=US&amp;SHIPTOCOUNTRYNAME=United%20States&amp;ADDRESSSTATUS= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomerDetails {
            get {
                return ResourceManager.GetString("CustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKEN=EC%2d5ED70123NJ325433P&amp;SUCCESSPAGEREDIRECTREQUESTED=false&amp;TIMESTAMP=2015%2d09%2d17T11%3a32%3a14Z&amp;CORRELATIONID=da59801663304&amp;ACK=Success&amp;VERSION=108%2e0&amp;BUILD=000000&amp;INSURANCEOPTIONSELECTED=false&amp;SHIPPINGOPTIONISDEFAULT=false&amp;PAYMENTINFO_0_TRANSACTIONID=6YX65164PA326324T&amp;PAYMENTINFO_0_TRANSACTIONTYPE=expresscheckout&amp;PAYMENTINFO_0_PAYMENTTYPE=instant&amp;PAYMENTINFO_0_ORDERTIME=2015%2d09%2d17T11%3a32%3a14Z&amp;PAYMENTINFO_0_AMT=19%2e95&amp;PAYMENTINFO_0_FEEAMT=0%2e93&amp;PAYMENTINFO_0_TAXAMT=0%2e00&amp;PAYMENTINFO_0_CURRE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DoExpressCheckoutPayment {
            get {
                return ResourceManager.GetString("DoExpressCheckoutPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMESTAMP=2015%2d09%2d02T16%3a19%3a49Z&amp;CORRELATIONID=d594df3b6b673&amp;ACK=Failure&amp;VERSION=78&amp;BUILD=000000&amp;L_ERRORCODE0=10002&amp;L_SHORTMESSAGE0=Security%20error&amp;L_LONGMESSAGE0=Security%20header%20is%20not%20valid&amp;L_SEVERITYCODE0=Error.
        /// </summary>
        internal static string ErrorResponse {
            get {
                return ResourceManager.GetString("ErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOKEN=EC%2d8JV062580S765292N&amp;TIMESTAMP=2015%2d09%2d02T16%3a04%3a05Z&amp;CORRELATIONID=6fccea464cc20&amp;ACK=Success&amp;VERSION=78&amp;BUILD=000000.
        /// </summary>
        internal static string SetExpressCheckout {
            get {
                return ResourceManager.GetString("SetExpressCheckout", resourceCulture);
            }
        }
    }
}
